image: debian/stable
packages:
  - ruby-full
  - ruby-dev
  - nodejs
  - rsync
  - libmagickwand-dev
sources:
  - https://git.sr.ht/~stfn/freehold-cottage
environment:
  deploy: sourcehut@stefn.co.uk:freehold-cottage
secrets:
  - 312fd5eb-95ad-4f33-9c83-fd5664236be4
tasks:
  - setup: |
      sudo gem install bundler
  - build: |
      cd freehold-cottage
      bundle install
      bundle exec jekyll build
  - deploy: |
      cd freehold-cottage
      ssh_opts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$ssh_opts" -rP _site/ $deploy


