image: alpine/edge
packages:
  - ruby-full
  - ruby-dev
  - nodejs
  - rsync
  - imagemagick
  - imagemagick-dev
  - imagemagick-libs
sources:
  - https://git.sr.ht/~stfn/freehold-cottage
secrets:
  - e674d338-b57a-4099-a057-dacf648ab7b3
tasks:
  - setup: |
      sudo gem install --no-document bundler
      sudo gem install --no-document neocities
  - build: |
      cd freehold-cottage
      bundle config jobs 4
      bundle install
      JEKYLL_ENV=production bundle exec jekyll build
  - deploy: |
      cd freehold-cottage
      set +x
      export NEOCITIES_API_KEY=$(cat ~/.neocities_api_key)
      set -x
      neocities push --prune _site
